// lib/mockData.js

// ─── Mock Purchase Orders ────────────────────────────
export const MOCK_PURCHASE_ORDERS = [
  {
    id: 'po-001',
    po_number: 'PO-001',
    title: 'Office Supplies Q1',
    description: 'Stationery and printer consumables for Q1',
    date: '2025-01-10',
    department: 'Operations',
    requires_ceo: false,
    status: 'approved',
    total: 1240.00,
    created_by: 'mock-pm-001',
    created_by_name: 'Alaa Mansour',
    approved_by: 'mock-ceo-001',
    approved_at: '2025-01-12T09:30:00Z',
    created_at: '2025-01-10T08:00:00Z',
    tags: ['monthly', 'supplies'],
    line_items: [
      { id: 'li-001', description: 'A4 Paper (10 reams)', price: 180.00 },
      { id: 'li-002', description: 'Printer Ink Cartridges x4', price: 320.00 },
      { id: 'li-003', description: 'Pens, folders, misc', price: 740.00 },
    ],
    attachments: [
      { id: 'att-001', file_name: 'invoice-office-supplies.pdf', file_path: '/mock/invoice-office-supplies.pdf', file_type: 'application/pdf', file_size: 204800 },
    ],
    audit: [
      { action: 'created', performed_by: 'Alaa Mansour', created_at: '2025-01-10T08:00:00Z' },
      { action: 'approved', performed_by: 'Marwan Idris', created_at: '2025-01-12T09:30:00Z' },
    ],
  },
  {
    id: 'po-002',
    po_number: 'PO-002',
    title: 'Server Infrastructure Upgrade',
    description: 'Additional cloud capacity for Q1 traffic spike',
    date: '2025-01-18',
    department: 'Engineering',
    requires_ceo: true,
    status: 'pending',
    total: 18500.00,
    created_by: 'mock-pm-001',
    created_by_name: 'Alaa Mansour',
    approved_by: null,
    approved_at: null,
    created_at: '2025-01-18T11:00:00Z',
    tags: ['urgent', 'infrastructure', 'Q1'],
    line_items: [
      { id: 'li-004', description: 'Cloud compute instances x6 (annual)', price: 12000.00 },
      { id: 'li-005', description: 'Storage expansion 10TB', price: 4500.00 },
      { id: 'li-006', description: 'Setup & migration service', price: 2000.00 },
    ],
    attachments: [
      { id: 'att-002', file_name: 'server-quote.pdf', file_path: '/mock/server-quote.pdf', file_type: 'application/pdf', file_size: 512000 },
    ],
    audit: [
      { action: 'created', performed_by: 'Alaa Mansour', created_at: '2025-01-18T11:00:00Z' },
    ],
  },
  {
    id: 'po-003',
    po_number: 'PO-003',
    title: 'Marketing Campaign — Social Media',
    description: 'Paid ads budget for Instagram and LinkedIn',
    date: '2025-01-20',
    department: 'Marketing',
    requires_ceo: false,
    status: 'pending',
    total: 4200.00,
    created_by: 'mock-sec-001',
    created_by_name: 'Layla Hassan',
    approved_by: null,
    approved_at: null,
    created_at: '2025-01-20T13:15:00Z',
    tags: ['marketing', 'Q1'],
    line_items: [
      { id: 'li-007', description: 'Instagram Ads Budget', price: 2500.00 },
      { id: 'li-008', description: 'LinkedIn Sponsored Posts', price: 1700.00 },
    ],
    attachments: [],
    audit: [
      { action: 'created', performed_by: 'Layla Hassan', created_at: '2025-01-20T13:15:00Z' },
    ],
  },
  {
    id: 'po-004',
    po_number: 'PO-004',
    title: 'Legal Retainer — January',
    description: 'Monthly retainer for corporate legal counsel',
    date: '2025-01-05',
    department: 'Legal',
    requires_ceo: false,
    status: 'approved',
    total: 3000.00,
    created_by: 'mock-pm-001',
    created_by_name: 'Alaa Mansour',
    approved_by: 'mock-ceo-001',
    approved_at: '2025-01-06T10:00:00Z',
    created_at: '2025-01-05T09:00:00Z',
    tags: ['monthly', 'retainer'],
    line_items: [
      { id: 'li-009', description: 'Legal counsel monthly fee', price: 3000.00 },
    ],
    attachments: [
      { id: 'att-004', file_name: 'legal-retainer-jan.pdf', file_path: '/mock/legal-retainer-jan.pdf', file_type: 'application/pdf', file_size: 307200 },
    ],
    audit: [
      { action: 'created', performed_by: 'Alaa Mansour', created_at: '2025-01-05T09:00:00Z' },
      { action: 'approved', performed_by: 'Marwan Idris', created_at: '2025-01-06T10:00:00Z' },
    ],
  },
  {
    id: 'po-005',
    po_number: 'PO-005',
    title: 'Sales Team Laptops',
    description: 'Replacement laptops for 3 new sales hires',
    date: '2025-01-22',
    department: 'Sales',
    requires_ceo: true,
    status: 'rejected',
    total: 6750.00,
    created_by: 'mock-pm-001',
    created_by_name: 'Alaa Mansour',
    approved_by: 'mock-ceo-001',
    approved_at: '2025-01-23T14:00:00Z',
    created_at: '2025-01-22T10:30:00Z',
    tags: ['hardware', 'onboarding'],
    line_items: [
      { id: 'li-010', description: 'Dell XPS 15 x3', price: 6750.00 },
    ],
    attachments: [
      { id: 'att-005', file_name: 'dell-quote.pdf', file_path: '/mock/dell-quote.pdf', file_type: 'application/pdf', file_size: 184320 },
    ],
    audit: [
      { action: 'created', performed_by: 'Alaa Mansour', created_at: '2025-01-22T10:30:00Z' },
      { action: 'rejected', performed_by: 'Marwan Idris', created_at: '2025-01-23T14:00:00Z' },
    ],
  },
]

// ─── Mock Employees ──────────────────────────────────
export const MOCK_EMPLOYEES = [
  {
    id: 'emp-001',
    full_name: 'Rania Aziz',
    title: 'Operations Manager',
    date_of_birth: '1982-03-15',
    salary: 4800.00,
    department: 'Operations',
    hire_date: '2018-06-01',
    is_active: true,
  },
  {
    id: 'emp-002',
    full_name: 'Tariq Nasser',
    title: 'Senior Engineer',
    date_of_birth: '1990-07-22',
    salary: 5600.00,
    department: 'Engineering',
    hire_date: '2020-03-15',
    is_active: true,
  },
  {
    id: 'emp-003',
    full_name: 'Dima Saad',
    title: 'Marketing Specialist',
    date_of_birth: '1995-11-08',
    salary: 3200.00,
    department: 'Marketing',
    hire_date: '2022-01-10',
    is_active: true,
  },
  {
    id: 'emp-004',
    full_name: 'Khalid Osman',
    title: 'Sales Executive',
    date_of_birth: '1988-05-30',
    salary: 3800.00,
    department: 'Sales',
    hire_date: '2019-09-01',
    is_active: true,
  },
  {
    id: 'emp-005',
    full_name: 'Lina Barakat',
    title: 'HR Specialist',
    date_of_birth: '1993-02-14',
    salary: 3400.00,
    department: 'HR',
    hire_date: '2021-05-20',
    is_active: true,
  },
  {
    id: 'emp-006',
    full_name: 'Sami Haddad',
    title: 'Legal Counsel',
    date_of_birth: '1979-09-03',
    salary: 6200.00,
    department: 'Legal',
    hire_date: '2016-11-15',
    is_active: true,
  },
  {
    id: 'emp-007',
    full_name: 'Yasmine Khoury',
    title: 'Finance Analyst',
    date_of_birth: '1991-06-18',
    salary: 4200.00,
    department: 'Finance',
    hire_date: '2020-08-01',
    is_active: true,
  },
  {
    id: 'emp-008',
    full_name: 'Omar Farouk',
    title: 'Junior Engineer',
    date_of_birth: '1998-12-25',
    salary: 3000.00,
    department: 'Engineering',
    hire_date: '2023-02-01',
    is_active: true,
  },
]

// ─── Mock Employment Requests ────────────────────────
export const MOCK_EMPLOYMENT_REQUESTS = [
  {
    id: 'er-001',
    er_number: 'ER-001',
    job_title: 'Frontend Developer',
    department: 'Engineering',
    salary_min: 4000.00,
    salary_max: 5500.00,
    tasks_description: 'Build and maintain React-based web applications. Collaborate with backend team on API integration. Own the design system implementation.',
    positions_count: 2,
    status: 'fulfilled',
    skills: ['React', 'TypeScript', 'SCSS', 'Git'],
    created_by: 'mock-pm-001',
    fulfilled_by: 'mock-hr-001',
    fulfilled_at: '2025-01-15T10:00:00Z',
    approved_by: null,
    approved_at: null,
    created_at: '2025-01-08T09:00:00Z',
  },
  {
    id: 'er-002',
    er_number: 'ER-002',
    job_title: 'Sales Executive',
    department: 'Sales',
    salary_min: 3000.00,
    salary_max: 4000.00,
    tasks_description: 'Manage client relationships, close deals, and grow regional accounts. Report to Sales Manager weekly.',
    positions_count: 1,
    status: 'open',
    skills: ['CRM', 'Negotiation', 'B2B Sales'],
    created_by: 'mock-pm-001',
    fulfilled_by: null,
    fulfilled_at: null,
    approved_by: null,
    approved_at: null,
    created_at: '2025-01-19T11:30:00Z',
  },
  {
    id: 'er-003',
    er_number: 'ER-003',
    job_title: 'Marketing Manager',
    department: 'Marketing',
    salary_min: 4500.00,
    salary_max: 6000.00,
    tasks_description: 'Lead the marketing team, own campaign strategy, manage budget allocation across channels.',
    positions_count: 1,
    status: 'approved',
    skills: ['Marketing Strategy', 'SEO', 'Paid Media', 'Analytics'],
    created_by: 'mock-pm-001',
    fulfilled_by: 'mock-hr-001',
    fulfilled_at: '2025-01-10T14:00:00Z',
    approved_by: 'mock-ceo-001',
    approved_at: '2025-01-13T09:00:00Z',
    created_at: '2025-01-05T08:00:00Z',
  },
]

// ─── Mock Audit Log ──────────────────────────────────
export const MOCK_AUDIT_LOG = [
  {
    id: 'al-001',
    entity_type: 'purchase_order',
    entity_id: 'po-001',
    action: 'created',
    performed_by: 'mock-pm-001',
    performed_by_name: 'Alaa Mansour',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'al-002',
    entity_type: 'purchase_order',
    entity_id: 'po-001',
    action: 'approved',
    performed_by: 'mock-ceo-001',
    performed_by_name: 'Marwan Idris',
    created_at: '2025-01-12T09:30:00Z',
  },
  {
    id: 'al-003',
    entity_type: 'purchase_order',
    entity_id: 'po-005',
    action: 'created',
    performed_by: 'mock-pm-001',
    performed_by_name: 'Alaa Mansour',
    created_at: '2025-01-22T10:30:00Z',
  },
  {
    id: 'al-004',
    entity_type: 'purchase_order',
    entity_id: 'po-005',
    action: 'rejected',
    performed_by: 'mock-ceo-001',
    performed_by_name: 'Marwan Idris',
    created_at: '2025-01-23T14:00:00Z',
  },
  {
    id: 'al-005',
    entity_type: 'employment_request',
    entity_id: 'er-001',
    action: 'created',
    performed_by: 'mock-pm-001',
    performed_by_name: 'Alaa Mansour',
    created_at: '2025-01-08T09:00:00Z',
  },
  {
    id: 'al-006',
    entity_type: 'employment_request',
    entity_id: 'er-001',
    action: 'fulfilled',
    performed_by: 'mock-hr-001',
    performed_by_name: 'Nour Khalil',
    created_at: '2025-01-15T10:00:00Z',
  },
]